# Global shared parameters
model_name: "time_series_model"
training_data_path: "samples.nyctaxi.trips"

# Environment specific overrides
environments:
  dev:
    catalog: "dev"
    schema: "mlops_blueprint"
    experiment_name: "/dev-mlops-blueprint-experiment"
    log_level: "DEBUG"
  sit:
    catalog: "sit"
    schema: "mlops_blueprint"
    experiment_name: "/sit-mlops-blueprint-experiment"
    log_level: "INFO"
  prod:
    catalog: "prod"
    schema: "mlops_blueprint"
    experiment_name: "/prod-mlops-blueprint-experiment"
    log_level: "INFO"
